package codegen

import (
	"go/parser"
	"go/token"
	"reflect"
	"strings"
	"testing"

	"github.com/coilyco/umbra/http/guardfile"
)

const fixture = `wrap ward-kdl ops forgejo {
	spec forgejo.swagger.v1.json
	base-url "forgejo.example/api/v1"
	auth header-token { header Authorization; prefix "token "; value ssm "/forgejo/api-token" }
	can read repos { op "repoGet" }
	can create repos { op "createCurrentUserRepo" }
	can delete repos { op "repoDelete" }
}`

func TestRenderProducesValidGo(t *testing.T) {
	gf, err := guardfile.Parse([]byte(fixture))
	if err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	out, err := Render(gf, "forgejo.guardfile.kdl")
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	// gofmt'd output must parse as a Go file.
	if _, err := parser.ParseFile(token.NewFileSet(), "main.go", out, parser.AllErrors); err != nil {
		t.Fatalf("generated source does not parse: %v\n%s", err, out)
	}
	src := string(out)
	for _, want := range []string{
		"// Code generated by umbra; DO NOT EDIT.",
		"//go:embed forgejo.guardfile.kdl",
		"//go:embed forgejo.swagger.lock.json.gz",
		"var embeddedSpec0 []byte",
		`Name: "ward-kdl"`,
		"specverb.Mount(app",
		`"https://forgejo.example/swagger.v1.json", "WARD_KDL_OPS_FORGEJO_SPEC"`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated source missing %q", want)
		}
	}
}

func TestRenderSetMergesIntoOneBinary(t *testing.T) {
	const awsFixture = `wrap ward-kdl ops aws {
		spec aws.swagger.v1.json
		base-url "aws.example.com/api/v1"
		auth header-token { header Authorization; prefix "token "; value ssm "/aws/api-token" }
		can list buckets { op "ListBuckets" }
	}`
	fj, err := guardfile.Parse([]byte(fixture))
	if err != nil {
		t.Fatalf("parse forgejo fixture: %v", err)
	}
	aws, err := guardfile.Parse([]byte(awsFixture))
	if err != nil {
		t.Fatalf("parse aws fixture: %v", err)
	}
	out, err := RenderSet(
		[]*guardfile.Guardfile{fj, aws},
		[]string{"forgejo.guardfile.kdl", "aws.guardfile.kdl"},
	)
	if err != nil {
		t.Fatalf("RenderSet: %v", err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "main.go", out, parser.AllErrors); err != nil {
		t.Fatalf("merged source does not parse: %v\n%s", err, out)
	}
	src := string(out)
	for _, want := range []string{
		"//go:embed forgejo.guardfile.kdl",
		"//go:embed aws.guardfile.kdl",
		"var embeddedGuardfile0 []byte",
		"var embeddedGuardfile1 []byte",
		`"WARD_KDL_OPS_FORGEJO_SPEC"`,
		`"WARD_KDL_OPS_AWS_SPEC"`,
		`Name: "ward-kdl"`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("merged source missing %q", want)
		}
	}
}

func TestRenderParamsExecOnly(t *testing.T) {
	out, err := RenderParams(SetParams{
		Binary:  "ward-kdl",
		HasExec: true,
		Mounts:  []Params{{Transport: TransportExec, Binary: "ward-kdl", GuardfileName: "aws.guardfile.kdl"}},
	})
	if err != nil {
		t.Fatalf("RenderParams: %v", err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "main.go", out, parser.AllErrors); err != nil {
		t.Fatalf("exec-only source does not parse: %v\n%s", err, out)
	}
	src := string(out)
	for _, want := range []string{"//go:embed aws.guardfile.kdl", "execverb.Mount(app", "cli/execverb"} {
		if !strings.Contains(src, want) {
			t.Errorf("exec-only source missing %q", want)
		}
	}
	// An exec-only binary must not pull in any spec-only seam, or Go rejects the
	// unused import.
	for _, absent := range []string{"specverb.Mount", "http/specverb", "ssmTokenResolver", "net/http", "embeddedSpec0"} {
		if strings.Contains(src, absent) {
			t.Errorf("exec-only source should not contain spec-only %q", absent)
		}
	}
}

func TestRenderParamsEmbedsExecFile(t *testing.T) {
	out, err := RenderParams(SetParams{
		Binary:  "ward-kdl",
		HasExec: true,
		Mounts: []Params{{
			Transport:     TransportExec,
			Binary:        "ward-kdl",
			GuardfileName: "measure.kdl",
			EmbeddedFiles: []EmbeddedFile{{Source: "scripts/measure.py", Name: "scripts/measure.py"}},
		}},
	})
	if err != nil {
		t.Fatalf("RenderParams: %v", err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "main.go", out, parser.AllErrors); err != nil {
		t.Fatalf("embedded exec source does not parse: %v\n%s", err, out)
	}
	src := string(out)
	for _, want := range []string{
		"//go:embed scripts/measure.py",
		`embedfile.Materialize("ward-kdl", embeddedSources())`,
		"_ = cleanup()",
		`"scripts/measure.py": {Path: "scripts/measure.py", Data: embeddedFile0_0}`,
		"EmbeddedFiles: embeddedFiles",
		"http/umbra/embedfile",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("embedded exec source missing %q\n%s", want, src)
		}
	}
}

func TestRenderParamsMixed(t *testing.T) {
	out, err := RenderParams(SetParams{
		Binary:  "ward-kdl",
		HasSpec: true,
		HasExec: true,
		Mounts: []Params{
			{Transport: TransportSpec, Binary: "ward-kdl", GuardfileName: "forgejo.guardfile.kdl", SpecLockName: "forgejo.swagger.lock.json.gz", SpecURL: "https://forgejo.example/swagger.v1.json", SpecEnvVar: "WARD_KDL_OPS_FORGEJO_SPEC", Providers: []string{"ssm"}, ProviderDecls: []guardfile.ProviderDecl{{Name: "ssm", Exec: []string{"aws", "ssm", "get-parameter"}}}},
			{Transport: TransportExec, Binary: "ward-kdl", GuardfileName: "aws.guardfile.kdl"},
		},
	})
	if err != nil {
		t.Fatalf("RenderParams: %v", err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "main.go", out, parser.AllErrors); err != nil {
		t.Fatalf("mixed source does not parse: %v\n%s", err, out)
	}
	src := string(out)
	for _, want := range []string{
		"specverb.Mount(app", "execverb.Mount(app",
		"//go:embed forgejo.swagger.lock.json.gz", "//go:embed aws.guardfile.kdl", `"ssm": execProvider(`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("mixed source missing %q", want)
		}
	}
	// The spec member (index 0) embeds a spec lock; the exec member (index 1) must not.
	if !strings.Contains(src, "embeddedSpec0") {
		t.Error("spec member (index 0) should have a spec-lock embed")
	}
	if strings.Contains(src, "embeddedSpec1") {
		t.Error("exec member (index 1) should not have a spec-lock embed")
	}
}

func TestPlanExecDerivesParams(t *testing.T) {
	p, err := PlanExec([]string{"ward-kdl", "ops", "aws"}, []string{"ssm"}, "aws.guardfile.kdl", nil)
	if err != nil {
		t.Fatalf("PlanExec: %v", err)
	}
	want := Params{Transport: TransportExec, Binary: "ward-kdl", GuardfileName: "aws.guardfile.kdl", Providers: []string{"ssm"}}
	if !reflect.DeepEqual(p, want) {
		t.Errorf("PlanExec = %+v, want %+v", p, want)
	}
}

func TestPlanExecRejectsEmptyGroup(t *testing.T) {
	if _, err := PlanExec(nil, nil, "x.kdl", nil); err == nil {
		t.Fatal("expected error for an exec Guardfile with no group")
	}
}

func TestRenderSetRejectsBinaryMismatch(t *testing.T) {
	const other = `wrap other ops aws {
		spec aws.swagger.v1.json
		base-url "aws.example.com/api/v1"
		auth header-token { header Authorization; prefix "token "; value ssm "/aws/api-token" }
		can list buckets { op "ListBuckets" }
	}`
	a, _ := guardfile.Parse([]byte(fixture))
	b, _ := guardfile.Parse([]byte(other))
	if _, err := RenderSet([]*guardfile.Guardfile{a, b}, []string{"a.kdl", "b.kdl"}); err == nil {
		t.Fatal("expected error when guardfiles disagree on binary name")
	}
}

func TestRenderRejectsEmptyGroup(t *testing.T) {
	if _, err := Render(&guardfile.Guardfile{}, "x.kdl"); err == nil {
		t.Fatal("expected error for a Guardfile with no group")
	}
}

func TestDeriveLockName(t *testing.T) {
	cases := map[string]string{
		"forgejo.swagger.v1.json":    "forgejo.swagger.lock.json.gz",
		"forgejo.swagger.v1.json.gz": "forgejo.swagger.lock.json.gz",
		"trello.openapi.json":        "trello.openapi.lock.json.gz",
		"trello.openapi.json.gz":     "trello.openapi.lock.json.gz",
		"tailscale.openapi.yaml":     "tailscale.openapi.lock.json.gz",
		"tailscale.openapi.yaml.gz":  "tailscale.openapi.lock.json.gz",
		"weird.spec":                 "weird.spec.lock.gz",
		"weird.spec.gz":              "weird.spec.lock.gz",
	}
	for in, want := range cases {
		if got := deriveLockName(in); got != want {
			t.Errorf("deriveLockName(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestDeriveSpecURL(t *testing.T) {
	cases := map[string]string{
		"forgejo.example/api/v1":         "https://forgejo.example/swagger.v1.json",
		"https://forgejo.example/api/v1": "https://forgejo.example/swagger.v1.json",
	}
	for in, want := range cases {
		got, err := deriveSpecURL(in)
		if err != nil {
			t.Fatalf("deriveSpecURL(%q): %v", in, err)
		}
		if got != want {
			t.Errorf("deriveSpecURL(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestPlanDerivesParams(t *testing.T) {
	gf, err := guardfile.Parse([]byte(fixture))
	if err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	p, err := Plan(gf, "forgejo.guardfile.kdl")
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	want := Params{
		Transport:     TransportSpec,
		Binary:        "ward-kdl",
		GuardfileName: "forgejo.guardfile.kdl",
		SpecLockName:  "forgejo.swagger.lock.json.gz",
		SpecURL:       "https://forgejo.example/swagger.v1.json",
		SpecEnvVar:    "WARD_KDL_OPS_FORGEJO_SPEC",
		Providers:     []string{"ssm"},
	}
	if !reflect.DeepEqual(p, want) {
		t.Errorf("Plan = %+v, want %+v", p, want)
	}
}

func TestPlanRejectsEmptyGroup(t *testing.T) {
	if _, err := Plan(&guardfile.Guardfile{}, "x.kdl"); err == nil {
		t.Fatal("expected error for a Guardfile with no group")
	}
}

// TestPlanBaseURLSSM proves a base-url-from-value member plans with an empty
// SpecURL (its spec is vendored, read locally at lock) and no error.
func TestPlanBaseURLSSM(t *testing.T) {
	gf, err := guardfile.Parse([]byte(`wrap ward-kdl ops open-webui {
		spec open-webui.openapi.json
		base-url { value ssm "/coilysiren/open-webui/url" }
		auth bearer { value ssm "/coilysiren/open-webui/api-key" }
		can get session { op "get_session_user_api_v1_auths__get" }
	}`))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	p, err := Plan(gf, "ward-kdl.open-webui.guardfile.kdl")
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if p.SpecURL != "" {
		t.Errorf("SpecURL = %q, want empty (no derivable host)", p.SpecURL)
	}
	if p.SpecLockName != "open-webui.openapi.lock.json.gz" {
		t.Errorf("SpecLockName = %q", p.SpecLockName)
	}
}

// TestPlanRejectsNoBase proves a spec member with neither base-url form is a
// fail-closed error: requests would have no host.
func TestPlanRejectsNoBase(t *testing.T) {
	gf := &guardfile.Guardfile{Group: []string{"ward-kdl", "ops", "x"}, Spec: "x.openapi.json"}
	if _, err := Plan(gf, "x.kdl"); err == nil {
		t.Fatal("expected error for a spec member with no base-url")
	}
}

// TestRenderWiresProvidersByUsage proves the codegen wires only the declared
// resolvers a member actually names; built-ins and undeclared names emit nothing.
func TestRenderWiresProvidersByUsage(t *testing.T) {
	gf, err := guardfile.Parse([]byte(`wrap ward-kdl ops owui {
		spec owui.openapi.json
		provider tailscale {
			exec tailscale ip -4
		}
		base-url { value tailscale "open-webui" }
		auth bearer { value env "OWUI_TOKEN" }
		can get session { op "get_session" }
	}`))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	out, err := Render(gf, "owui.guardfile.kdl")
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "main.go", out, parser.AllErrors); err != nil {
		t.Fatalf("generated source does not parse: %v\n%s", err, out)
	}
	src := string(out)
	for _, want := range []string{"providerRegistry", "execProvider(", `"tailscale": execProvider("tailscale", []string{"tailscale", "ip", "-4"})`} {
		if !strings.Contains(src, want) {
			t.Errorf("generated source missing %q", want)
		}
	}
	// env is a umbra built-in: no codegen, and no store SDK in use.
	for _, absent := range []string{"aws-sdk-go-v2", "awsconfig", `"ssm":`} {
		if strings.Contains(src, absent) {
			t.Errorf("generated source should not contain %q (no ssm in use)", absent)
		}
	}
}

// TestRenderWiresPlacementHint covers what an operator sees when a wrapped
// tool's flag lands before the verb: without it the parse error reads as a refusal.
func TestRenderWiresPlacementHint(t *testing.T) {
	gf, err := guardfile.Parse([]byte(fixture))
	if err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	out, err := Render(gf, "forgejo.guardfile.kdl")
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "main.go", out, parser.AllErrors); err != nil {
		t.Fatalf("generated source does not parse: %v", err)
	}
	src := string(out)
	for _, want := range []string{
		"OnUsageError: placementHint",
		"func placementHint(",
		"func hintPlacement(",
		"hintPlacement(app.Commands)",
		"flag provided but not defined",
		"not a denied capability",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated source is missing %q", want)
		}
	}
}

// TestRender_GeneratedMainHonoursTheTaxonomy guards umbra#341: the template
// printed a coded error and exited 1, discarding the code the engines build.
func TestRender_GeneratedMainHonoursTheTaxonomy(t *testing.T) {
	gf, err := guardfile.Parse([]byte(fixture))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	main, err := Render(gf, "forgejo.guardfile.kdl")
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	src := string(main)
	for _, want := range []string{
		"os.Exit(exitcode.Of(err))",
		"os.Exit(exitcode.UserError)",
		"CommandNotFound: unknownVerb",
		"umbra/pkg/exitcode",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated main is missing %q", want)
		}
	}
	// The flat exit that made the taxonomy unreadable must not come back.
	if strings.Contains(src, "os.Exit(1)") {
		t.Error("generated main still exits 1 on a coded error")
	}
}

// replacementParams is the shape the driver plans for a `replace` member: one
// exec mount, and the binary named for the tool rather than for a driver.
func replacementParams() SetParams {
	return SetParams{
		Binary:   "git",
		HasExec:  true,
		Replace:  true,
		Occluded: "git",
		Mounts: []Params{{
			Transport:     TransportExec,
			Binary:        "git",
			GuardfileName: "git.guardfile.kdl",
			Replace:       true,
			Occluded:      "git",
		}},
	}
}

func TestRenderParamsReplacementIsTheToolItself(t *testing.T) {
	out, err := RenderParams(replacementParams())
	if err != nil {
		t.Fatalf("RenderParams: %v", err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "main.go", out, parser.AllErrors); err != nil {
		t.Fatalf("replacement source does not parse: %v\n%s", err, out)
	}
	src := string(out)
	for _, want := range []string{
		"execverb.BuildReplacement",
		"execverb.InstallFallback",
		"execverb.IdentifyEnv",
		"execverb.RootFlagFallback",
		"execverb.NewFallback",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("replacement source missing %q", want)
		}
	}
	// The grants are the tool's own verbs, so nothing mounts under a driver
	// group and no urfave Version flag is registered over the tool's own.
	for _, absent := range []string{"execverb.Mount(app", "Version: Version"} {
		if strings.Contains(src, absent) {
			t.Errorf("replacement source should not contain %q", absent)
		}
	}
}

func TestRenderParamsRefusesAMergedReplacement(t *testing.T) {
	sp := replacementParams()
	sp.Mounts = append(sp.Mounts, Params{Transport: TransportExec, Binary: "git", GuardfileName: "gh.guardfile.kdl"})
	if _, err := RenderParams(sp); err == nil {
		t.Fatal("a replacement merged with a second member must fail closed: it would mount verbs the occluded tool does not have")
	}
}

func TestRenderParamsRefusesAnUnplannedReplacementMember(t *testing.T) {
	sp := replacementParams()
	sp.Replace, sp.Occluded = false, ""
	if _, err := RenderParams(sp); err == nil {
		t.Fatal("a member declaring `replace` under a binary not planned as one must fail closed")
	}
}
